# Generated by Django 3.1.7 on 2021-03-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_tipodespesapessoal_tiporeceitapessoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
    ]
