# Generated by Django 3.1.7 on 2021-03-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_pessoa_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'verbose_name': 'Tipo de Despesa Padrão', 'verbose_name_plural': 'Tipos de Despesa Padrão'},
        ),
        migrations.AlterModelOptions(
            name='tiporeceita',
            options={'verbose_name': 'Tipo de Receita Padrão', 'verbose_name_plural': 'Tipos de Receita Padrão'},
        ),
        migrations.AlterModelOptions(
            name='tiporeceitapessoal',
            options={'verbose_name': 'Tipo de Receita', 'verbose_name_plural': 'Tipos de Receita'},
        ),
    ]
