# Generated by Django 3.0.7 on 2020-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, default='!', max_length=255, null=True, verbose_name='Senha')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('groups', models.ManyToManyField(blank=True, to='api.Group', verbose_name='Grupos')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
