# Generated by Django 3.1.5 on 2021-01-25 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slothy.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, default='!', max_length=255, null=True, verbose_name='Senha')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=255, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor', slothy.db.models.fields.ColorField(default='#FFFFFF', max_length=10, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(verbose_name='DDD')),
                ('numero', models.CharField(max_length=255, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.pessoa')),
            ],
            options={
                'verbose_name': 'Presidente',
                'verbose_name_plural': 'Presidentes',
            },
            bases=('base.pessoa',),
        ),
        migrations.CreateModel(
            name='Governador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', slothy.db.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado', verbose_name='Estado')),
                ('pessoa', slothy.db.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Governador',
                'verbose_name_plural': 'Governadores',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('cidade', slothy.db.models.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=slothy.db.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pontos_turisticos',
            field=models.ManyToManyField(blank=True, to='base.PontoTuristico', verbose_name='Pontos Turísticos'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='prefeito',
            field=slothy.db.models.fields.RoleForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Prefeito'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='vereadores',
            field=slothy.db.models.fields.RoleManyToManyField(blank=True, related_name='cidades_legisladas', to=settings.AUTH_USER_MODEL, verbose_name='Vereadores'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=slothy.db.models.fields.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='groups',
            field=models.ManyToManyField(blank=True, to='api.Group', verbose_name='Grupos'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefones',
            field=slothy.db.models.fields.OneToManyField(to='base.Telefone', verbose_name='Telefones'),
        ),
    ]
