# Generated by Django 3.1.5 on 2021-01-29 06:07

from django.db import migrations
import slothy.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=slothy.db.models.fields.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=slothy.db.models.fields.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='cor',
            field=slothy.db.models.fields.ColorField(blank=True, default='#FFFFFF', max_length=10, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=slothy.db.models.fields.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=slothy.db.models.fields.CpfField(max_length=255, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=slothy.db.models.fields.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='password',
            field=slothy.db.models.fields.CharField(blank=True, default='!', max_length=255, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=slothy.db.models.fields.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=slothy.db.models.fields.CharField(max_length=255, verbose_name='Telefone'),
        ),
    ]
