# Generated by Django 2.0 on 2020-12-24 02:29

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import slothy.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='governador',
            name='pessoa',
            field=slothy.api.models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
