# Generated by Django 3.1.5 on 2021-01-31 17:24

from django.db import migrations
import slothy.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20210129_0606'),
        ('base', '0002_auto_20210129_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enderecos.municipio',),
        ),
        migrations.AddField(
            model_name='cidade',
            name='localizacao',
            field=slothy.db.models.fields.GeoLocationField(max_length=255, null=True, verbose_name='Localização'),
        ),
    ]
