# Generated by Django 2.0 on 2020-12-30 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slothy.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201224_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(verbose_name='DDD')),
                ('numero', models.CharField(max_length=255, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.AlterField(
            model_name='cidade',
            name='pontos_turisticos',
            field=models.ManyToManyField(blank=True, to='base.PontoTuristico', verbose_name='Pontos Turísticos'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='prefeito',
            field=slothy.api.models.RoleForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Prefeito'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefones',
            field=slothy.api.models.OneToManyField(to='base.Telefone', verbose_name='Telefones'),
        ),
    ]
