# Generated by Django 2.0 on 2021-01-02 13:01

from django.db import migrations
import django.db.models.deletion
import slothy.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210102_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=slothy.api.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Cidade', verbose_name='Cidade'),
        ),
    ]
