# Generated by Django 2.0 on 2020-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200622_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
