# Generated by Django 2.0 on 2020-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_estado_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='nome',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
