# Generated by Django 3.1.5 on 2021-01-25 05:08

from django.db import migrations
import slothy.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210116_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='cor',
            field=slothy.api.models.ColorField(default='#FFFFFF', max_length=10, verbose_name='Cor'),
        ),
    ]
