# Generated by Django 3.1.7 on 2021-03-06 14:20

from django.db import migrations
import slothy.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=slothy.db.models.fields.CharField(default=None, max_length=255, unique=True, verbose_name='Login'),
            preserve_default=False,
        ),
    ]
