# Generated by Django 3.1.5 on 2021-02-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210131_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
