app.base.estado.all().print()
e=app.base.estado.add({sigla: 'RJ'})
e.get_cidades().print()
c=e.get_cidades().add({nome: 'Rio de Janeiro'})
c.get_pontos_turisticos().print()
pt=c.get_pontos_turisticos().add({nome:'ZZZZZ'})
c.get_pontos_turisticos().print()
c.get_pontos_turisticos().remove(pt)
c.get_pontos_turisticos().print()
c.get_pontos_turisticos().add(pt)
c.get_pontos_turisticos().print()
c.get_pontos_turisticos().remove(pt.id)
c.get_pontos_turisticos().print()
c.get_pontos_turisticos().add(pt.id)
c.get_pontos_turisticos().print()
pt.delete()
c.get_pontos_turisticos().print()
e.get_cidades().remove(c)
e.get_cidades().print()
e.delete()
app.base.estado.all().print()