app.base.estado.all().log()
e=app.base.estado.add({sigla: 'RJ'})
e.get_cidades().log()
c=e.get_cidades().add({nome: 'Rio de Janeiro'})

app.base.pontoturistico.all().log()
c=app.base.cidade.get(c.id)
c.get_pontos_turisticos().log()
pt=c.get_pontos_turisticos().add({nome:'ZZZZZ'})
c.get_pontos_turisticos().log()
c.get_pontos_turisticos().remove(pt.id)
c.get_pontos_turisticos().log()
c.get_pontos_turisticos().add(pt.id)
c.get_pontos_turisticos().log()
pt=app.base.pontoturistico.get(pt.id)
pt.delete()
c.get_pontos_turisticos().log()

e.get_cidades().remove(c.id)
e.delete()